apache/maven-javadoc-plugin

- pom.xml
- src/it/projects/MJAVADOC-538/invoker.properties
- src/it/projects/MJAVADOC-538/pom.xml
- src/it/projects/MJAVADOC-538/src/main/java/foo/bar/MyClass.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
Tested with:
* `mvn -Prun-its verify`
Additional testing on project I was having original issues
* `mvn install`
* `export JAVA_TOOL_OPTIONS="-Dapple.awt.UIElement=true"`
* Set pom for project to use 3.0.2-SNAPSHOT
```
<pluginManagement>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-javadoc-plugin</artifactId>
<version>3.0.2-SNAPSHOT</version>
</plugin>
</plugins>
</pluginManagement>
```
* Ran the following on my project - `mvn -Dmaven.javadoc.failOnError=true -Dmaven.javadoc.failOnWarnings=true javadoc:javadoc javadoc:test-javadoc`
Prior to this change was getting failure from warning "Picked up ...". With this change, Javadoc no longer fails due to warning.
> [MJAVADOC-538] Filter out 'Picked up'

- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
To prevent a warning about a missing input stream we explicitly set
batchMode when invoking other maven commands
fixes MJAVADOC-537
> [MJAVADOC-537] Explicitly the batchMode to true

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
- src/test/java/org/apache/maven/plugins/javadoc/stubs/OptionsUmlautEncodingMavenProjectStub.java
- src/test/resources/unit/optionsumlautencoding-test/optionsumlautencoding-test-plugin-config.xml
- src/test/resources/unit/optionsumlautencoding-test/optionsumlautencoding/test/App.java
- src/test/resources/unit/optionsumlautencoding-test/optionsumlautencoding/test/AppSample.java
mvn -Prun-its verify was run with JDK9 on windows without errors
> [MJAVADOC-544] - Changed behaviour of Javadoc for temporary files encoding (options, argfile, ...)

- src/it/projects/MJAVADOC-444/invoker.properties
- src/it/projects/MJAVADOC-444/moduleA/pom.xml
- src/it/projects/MJAVADOC-444/moduleA/src/main/java/com/mycompany/myapp/AppA.java
- src/it/projects/MJAVADOC-444/moduleA/src/test/java/com/mycompany/myapp/AppATest.java
- src/it/projects/MJAVADOC-444/moduleB/pom.xml
- src/it/projects/MJAVADOC-444/moduleB/src/main/java/com/mycompany/myapp/AppB.java
- src/it/projects/MJAVADOC-444/moduleB/src/test/java/com/mycompany/myapp/AppBTest.java
- src/it/projects/MJAVADOC-444/pom.xml
- src/it/projects/MJAVADOC-444/verify.bsh
- src/main/java/org/apache/maven/plugins/javadoc/AggregatorJavadocNoForkReport.java
- src/main/java/org/apache/maven/plugins/javadoc/AggregatorTestJavadocNoForkReport.java
- src/site/apt/examples/aggregate-nofork.apt.vm
- src/site/apt/index.apt.vm
- src/site/site.xml
Follows the same pattern as JavadocNoForkReport with the aggregate goals.
Tested out locally by installing a SNAPSHOT version and then moving my project over to it.
> [MJAVADOC-444] add aggregate-no-fork and aggregate-test-no-fork for non-forking versions of aggregate goals.

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
Updated testCustomConfiguration() because JDK 11.0.2 behaves the same as JDK 12.
> Avoid converting separator characters into newline.

- src/site/apt/usage.apt.vm
I have modified the Wrong closing tag in the user's guide at 'https://maven.apache.org/plugins/maven-javadoc-plugin/usage.html'.
ticket : https://issues.apache.org/jira/browse/MJAVADOC-577
thank you for reading.
> [MJAVADOC-577] Fixed typos in User Guide.

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Sorry, a lot of unrelated changes because git normalized line endings...
> Fix typo in additionalDependencies documentation

- src/it/projects/MJAVADOC-620_no-dot-in-version/invoker.properties
- src/it/projects/MJAVADOC-620_no-dot-in-version/maven-MJAVADOC620-jar/pom.xml
- src/it/projects/MJAVADOC-620_no-dot-in-version/maven-MJAVADOC620-jar/src/main/java/somepackage/Test.java
- src/it/projects/MJAVADOC-620_no-dot-in-version/pom.xml
- src/it/projects/MJAVADOC-620_no-dot-in-version/src/main/java/TestUsage.java
- src/it/projects/MJAVADOC-620_no-dot-in-version/verify.bsh
- src/it/projects/MJAVADOC-620_top-level-package/invoker.properties
- src/it/projects/MJAVADOC-620_top-level-package/maven-MJAVADOC620-jar/pom.xml
- src/it/projects/MJAVADOC-620_top-level-package/maven-MJAVADOC620-jar/src/main/java/Test.java
- src/it/projects/MJAVADOC-620_top-level-package/pom.xml
- src/it/projects/MJAVADOC-620_top-level-package/src/main/java/TestUsage.java
- src/it/projects/MJAVADOC-620_top-level-package/verify.bsh
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
When `locationManager.resolvePaths()` processes JARs that do not define a module name, module-name-guessing is triggered. The last resort is to use the JAR's file name to derive a module name. The heuristic is to determine where a version number starts, for which the regex is used: `"-(\\d+(\\.|$))"`
See [JavaDoc of ModuleFinder.of()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/module/ModuleFinder.html#of(java.nio.file.Path...)).
For the remaining prefix, all non-alphanumeric characters (this includes dashes) are replaced by dots. When splitting at the dots, every part must be a legal Java identifier.
Now, when a Maven JAR uses the version `1-SNAPSHOT`, the JAR is named `<artifactId>-1-SNAPSHOT.jar`, so the version suffix is not recognized by the heuristic (the …
> [MJAVADOC-620] Do not ignore JARs w/o module info when building classpath

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/StaleHelper.java
PR to compute the state of a javadoc generation and skip the generation in case there is no change.
> [MJAVADOC-626] Add a stale javadoc detection mechanism

- src/main/java/org/apache/maven/plugins/javadoc/StaleHelper.java
> [MJAVADOC-644] Properly close DirectoryStream

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
@michael-o Starting work on clearing out some old code so we can update plexus and aether. Also fixes some API docs
> Uses try with resources

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/ClassWithJavadoc.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/ClassWithNoJavadoc.java
- src/test/resources/unit/fix-test/src/main/java/fix/test/ClassWithJavadoc.java
- src/test/resources/unit/fix-test/src/main/java/fix/test/ClassWithNoJavadoc.java
> [MJAVADOC-659] changing exception description when using "fix".

- src/main/java/org/apache/maven/plugins/javadoc/StaleHelper.java
Replaces the usage of the full commandline by only its arguments to generate the stale javadoc detection key.
This approach allows to handle file-arguments appropriately in case of double-quoting by resolving them to their actual arguments.
> [MJAVADOC-664] - Fix stale javadoc data detection on Windows.

- pom.xml
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocUtilTest.java
- src/test/java/org/apache/maven/plugins/javadoc/ProxyServer.java
> [MJAVADOC-687] Upgrade Jetty Version to last 9.4.x

- src/it/projects/examples/alternate-doclet/pom.xml
[MJAVADOC-475](https://issues.apache.org/jira/browse/MJAVADOC-475?focusedCommentId=16516951&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16516951):
> The documentation still uses the old additionalparams: https://maven.apache.org/plugins/maven-javadoc-plugin/examples/alternate-doclet.html
>
> This is not supposed to work anymore, or is it?
> (doc) Update plugin' configuration parameter (MJAVADOC-475)

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocJar.java
> [MJAVADOC-719] - Update Maven Archiver to 3.6.0

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/JavadocReport.java
>  [MJAVADOC-723] Upgrade Maven Reporting API to 3.1.1/Complete with Maven Reporting Impl 3.2.0

- src/site/apt/examples/stylesheet-configuration.apt.vm
document 'addStylesheets' as recommended way of configuring stylesheets
> [MJAVADOC-685] no longer document deprecated parameter stylesheet

- .github/pull_request_template.md
licence (double c's) is only used when the word is a noun, not a verb
@slachiewicz
> licenced --> licensed

- pom.xml
Dependency upgrade to common-text 1.10.0
---
https://issues.apache.org/jira/browse/MJAVADOC-738
> [MJAVADOC-738] Upgrade commons-text to 1.10.0

- src/site/fml/faq.fml
Sun --> Oracle
Oxford comma
update URLs
@michael-o
> Assorted minor FAQ edits

- src/site/apt/examples/fix-javadocs.apt.vm
> Clean up language and update URLs

- src/site/apt/examples/alternate-doclet.apt.vm
This fixes a link to umlgraph dot org in the site examples that now leads to an SEO farm. See here for reference: https://urlscan.io/result/08d37cce-364f-4bc7-a09f-e1afd7175c09/
[Individual Contributor …
> Fix UmlGraph link in site example

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocReport.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocVersion.java
- src/main/java/org/apache/maven/plugins/javadoc/TestJavadocReport.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
If your pull request …
> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

- pom.xml
Closes low-priority CVE-2023-26049 Dependabot report
> Bump jetty from 9.4.50.v20221201 to 9.4.51.v20230217

- src/it/projects/MJAVADOC-767/doc/pom.xml
- src/it/projects/MJAVADOC-767/invoker.properties
- src/it/projects/MJAVADOC-767/pom.xml
- src/it/projects/MJAVADOC-767/thing1/pom.xml
- src/it/projects/MJAVADOC-767/thing1/src/main/java/jdbug/thing1/Main.java
- src/it/projects/MJAVADOC-767/thing1/src/main/java/module-info.java
- src/it/projects/MJAVADOC-767/thing2/pom.xml
- src/it/projects/MJAVADOC-767/thing2/src/main/java/jdbug/thing2/Main.java
- src/it/projects/MJAVADOC-767/thing2/src/main/java/module-info.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
When using an exclude filter, it is possible that the plugin creates
javadoc --patch-module command line options, that do not actually have
a value.
This changes skips such empty entries.
[Individual …
> [MJAVADOC-767] javadoc creates invalid --patch-module statements

- src/it/projects/MJAVADOC-770/invoker.properties
- src/it/projects/MJAVADOC-770/pom.xml
- src/it/projects/MJAVADOC-770/src/main/java/mjavadoc770/Main.java
- src/it/projects/MJAVADOC-770/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
A lot of existing projects that don't use module descriptors but only
automatic module naming have moved past Java 8. However, when trying
to build docs, the javadoc plugin assumes that the project is
modularized and starts using the module path which leads to problems
with documentation generation.
This change introduces a new configuration setting `<legacyMode>`
which is turned off by default. When turning on, the javadoc plugin
will continue to construct just a classpath (and not a module path)
for the javadoc tool, even if the jdk version is 9 or greater.
Includes integration test and documentation.
require a …
> [MJAVADOC-770] Implement legacy mode for Java 9+

- src/it/projects/MJAVADOC-769/invoker.properties
- src/it/projects/MJAVADOC-769/pom.xml
- src/it/projects/MJAVADOC-769/src/main/java/mavenbugs/mjavadoc769/InternalImportBindingBuilder.java
- src/it/projects/MJAVADOC-769/src/test/java/mavenbugs/mjavadoc769/Right.java
- src/it/projects/MJAVADOC-769/src/test/java/mavenbugs/mjavadoc769/RightTest.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
When a project depends on an artifact with a manifest entry for
Automatic-Module-Name which in turn depends on an artifact that uses the
filename to determine the module name, it will move the former onto the
module path and patch the latter into the main artifact. However, now
the direct dependency on the module path can no longer access the
classes that have been patched only into the main module and javadoc
generation fails.
As the JDK only differentiates between modules with a module descriptor
and "everything else" (modules with an automatic module entry in the
manifest and modules with file name based names), the javadoc plugin
should do the same.
This patch changes the treatment of dependencies with an
Automatic-Module-Name to match dependencies that use a filename based
module …
> [MJAVADOC-769] fix for transitive filename based modules

- src/it/projects/MJAVADOC-642/invoker.properties
- src/it/projects/MJAVADOC-642/pom.xml
- src/it/projects/MJAVADOC-642/src/main/java/mjavadoc642/Main.java
- src/it/projects/MJAVADOC-642/verify.groovy
- src/it/projects/MJAVADOC-642_cmdline/invoker.properties
- src/it/projects/MJAVADOC-642_cmdline/pom.xml
- src/it/projects/MJAVADOC-642_cmdline/src/main/java/mjavadoc642/Main.java
- src/it/projects/MJAVADOC-642_cmdline/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/resources/unit/custom-configuration/custom-configuration-plugin-config.xml
expose the offline flag as a property (and a setting).
To make clear …
> [MJAVADOC-642] Make offline mode configurable

- src/it/projects/MJAVADOC-642/pom.xml
- src/it/projects/MJAVADOC-642/src/main/java/mjavadoc642/Main.java
- src/it/projects/MJAVADOC-642_cmdline/pom.xml
- src/it/projects/MJAVADOC-642_cmdline/src/main/java/mjavadoc642/Main.java
- src/it/projects/MJAVADOC-770/src/main/java/mjavadoc770/Main.java
On Jenkins we also use Maven 3.6.3
we need specified maven.compiler.target/source at least
---
please ask …
> Fix build on jenkins

- pom.xml
without such optional profile, build requires the plugin build to be already installed
fixes issue inadvertently introduced in #164
> MJAVADOC-774 create dev profile

- src/main/java/org/apache/maven/plugins/javadoc/JavadocReport.java
No actual code changes so if MJAVADOC-427 IT fails, we can believe it's broken in the CI
> [MJAVADOC-726] trivial Javadoc fixes to test state of CI

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
Alternate approach to keeping log4j out of the tree by excluding velocity-tools.
Nuked log4j from my .m2/repo and verified that the sample project does not download log4j when generating javadoc with 3.6.1-SNAPSHOT with this patch
Tests pass locally
> [MJAVADOC-726] exclude velocity

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/StaleHelper.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocJarTest.java
- src/test/resources/unit/stale-test/src/main/java/maven/App.java
- src/test/resources/unit/stale-test/stale-test-plugin-config.xml
> [MJAVADOC-716] Fix stale files detection failing because of the newline

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/AggregatorJavadocReportTest.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocJarTest.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
- src/test/java/org/apache/maven/plugins/javadoc/TestJavadocReportTest.java
> [MJAVADOC-782] Align read-only parameters naming with other plugins

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
This fixes also https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#addStylesheets which is currently rendered as:
---
> Fix `addStylesheets` Javadoc

- src/site/apt/usage.apt.vm
The "usage" documentation page mention the default value of the `nohelp` parameter being `true`, but it's `false` (https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#nohelp).
> Fix usage documentation mentioning `nohelp` default value

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> [MJAVADOC-796] Do not follow links for Java 12+

- src/it/projects/javadoc-fix/verify.bsh
- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/ClassWithJavadoc.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/ClassWithNoJavadoc.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/InterfaceWithJavadoc.java
- src/test/resources/unit/fix-test/expected/src/main/java/fix/test/InterfaceWithNoJavadoc.java
As mentioned in [MJAVADOC-799](https://issues.apache.org/jira/browse/MJAVADOC-799) there is currently a mismatch for the `AbstractFixJavadocMojo#defaultVersion` parameter default value:
- documented value: `$Id:$`
- initial field value: `$Id: $`
- `@Parameter#defaultValue`: `$Id: $Id`
It seems `@Parameter#defaultValue` overwrites the initial field value. This can be seen when running `mvn org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:fix` on a dummy project; it will add `@version $Id: $Id` to the Javadoc.
As mentioned in the Jira issue I am not sure if `$Id: $Id` is really a good / the intended default value, but it is the value currently used by the Mojo, therefore I have kept it. And I have adjusted the expected unit test results because they don't seem to create the Mojo instance …
> [MJAVADOC-799] Remove inconsistent `AbstractFixJavadocMojo#defaultVersion` default value

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/site/apt/examples/fix-javadocs.apt.vm
> [MJAVADOC-801] Upgrade to Clirr Maven Plugin 2.8 in fix goals

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocUtilTest.java
Fixes [MJAVADOC-775](https://issues.apache.org/jira/browse/MJAVADOC-775).
Fixes [MJAVADOC-783](https://issues.apache.org/jira/browse/MJAVADOC-783).
@elharo, @robjg, @jkesselm
---
> [MJAVADOC-775] Option 'taglets/taglet/tagletpath' ignored when pointing to a JAR

- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
> [MJAVADOC-804] Remove temporary directories created by tests

- src/it/projects/javadoc-fix-version/invoker.properties
- src/it/projects/javadoc-fix-version/pom.xml
- src/it/projects/javadoc-fix-version/src/main/java/fix/test/ClassWithJavadoc.java
- src/it/projects/javadoc-fix-version/src/main/java/fix/test/ClassWithJavadocAndVersion.java
- src/it/projects/javadoc-fix-version/src/main/java/fix/test/ClassWithNoJavadoc.java
- src/it/projects/javadoc-fix-version/verify.bsh
See https://github.com/apache/maven-javadoc-plugin/pull/295#issuecomment-2227104630; currently there is no test for a custom `FixJavadocMojo#defaultVersion` value.
I am not that familiar with the Invoker Plugin and the test setup here, so please let me know if I should change anything. I also tried to match the existing Java code formatting style.
----
is to use the JIRA issue title in the pull request title and in the first line …
> Add test for custom `FixJavadocMojo#defaultVersion`

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> Improve URL handling

- src/it/projects/MJAVADOC-257/mymojo/pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
As request carries the "effective" value (default or user overriden ones) but it does not mean they exist. And as invoker used, effect is same as user would use -s/-t CLI commands with non-existent files: mvn CLI failure.
> [MJAVADOC-810] [REGRESSION] MJAVADOC-791 causes forked Maven execution fail if any toolchains or settings file isn't present

- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/e1/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/e1/src/main/java/a/b/e/E1.java
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> [MJAVADOC-822] skippedModules should be more scalable and support regex

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/resolver/ResourceResolver.java
As seen on https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=181305684#MavenEcosystemCleanup-DropPlexusContainerforJSR-330+SisuGuiceextension
- Leverages https://github.com/openrewrite/rewrite-apache/pull/41
I have another two lined up for apache/maven and apache/maven-archetype that I'll verify first.
@elharo if you wouldn't mind, could you look this over?
Use this link to re-run the recipe: https://app.moderne.io/builder/P4zH7djn6?organizationId=QXBhY2hlIE1hdmVu
> refactor: Replace Plexus AbstractLogEnabled with SLF4J

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocUtilTest.java
> [MJAVADOC-814] handle parameters such packages with multi lines

- src/it/projects/MJAVADOC-823/b/c/d1/pom.xml
- src/it/projects/MJAVADOC-823/b/c/d1/src/main/java/a/b/c/d/D1.java
- src/it/projects/MJAVADOC-823/b/c/d1/src/main/java/module-info.java
- src/it/projects/MJAVADOC-823/b/c/d2/pom.xml
- src/it/projects/MJAVADOC-823/b/c/d2/src/main/java/a/b/c/d/D2.java
- src/it/projects/MJAVADOC-823/b/c/pom.xml
- src/it/projects/MJAVADOC-823/b/e/pom.xml
- src/it/projects/MJAVADOC-823/b/e/src/main/java/a/b/e/E.java
- src/it/projects/MJAVADOC-823/b/pom.xml
- src/it/projects/MJAVADOC-823/f/pom.xml
- src/it/projects/MJAVADOC-823/f/src/main/java/a/f/F.java
- src/it/projects/MJAVADOC-823/invoker.properties
- src/it/projects/MJAVADOC-823/pom.xml
- src/it/projects/MJAVADOC-823/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocReport.java
> [MJAVADOC-823] legacyMode keeps using module-info.java (-sourcedirectory still use as well as java files input)

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/TestJavadocJarMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/TestJavadocReport.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase
> Specify locale for case conversion

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Teeny tiny change to add a / to the end tag in an example in a javadoc for the links configuration.
> (doc) Close links tag in links parameter javadoc example

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
The aggregate javadoc mojo was calling `addAll` directly on the list returned by `project.getCompileSourceRoots`. This bug was silently ignored by Maven 3, but results in an `UnsupportedOperationException` on Maven 4.
Do a defensive copy instead.
If your pull request is about ~20 …
> [MJAVADOC-826] - Don't try to modify project source roots

- src/site/apt/index.apt.vm
> Correct javadoc-no-fork description on index-page

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
The `aggregate` mojo's [site](https://maven.apache.org/plugins/maven-javadoc-plugin/aggregate-mojo.html#docfilessubdirs) contains a typo for the `docfilessubdirs` property.
> Fix `aggregate` Javadoc typo

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/TestJavadocReport.java
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
> Issue #378 Cleanup of code related to old non supported Java version

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> Clean up comments and argument names

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocJarMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocJarMojoTest.java
On the happy path, just generate the Javadocs and don't bother the user excessively about every step of the process
> Reduce non-debug logging

- src/it/projects/MJAVADOC-770/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
This commit reverts the behavior introduced in d3fbbda8cf67fafd69ffe54ec0170e5aeb9e1166, after which a warning about the `-1.1` switch appears unconditionally. The warning, "Javadoc 1.4+ doesn't support the -1.1 switch anymore. Ignore this option." now only displays if the `old` parameter is set to true, as it did previously.
---
> Remove Javadoc 1.4+ / -1.1 switch related warning

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/main/java/org/apache/maven/plugins/javadoc/JavadocJarMojo.java
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
> detectOfflineLinks is now false per default for all *jar* mojo  issue #1258 

- src/it/projects/GITHUB-1242/invoker.properties
- src/it/projects/GITHUB-1242/pom.xml
- src/it/projects/GITHUB-1242/src/main/java/com/fruit/Fruits.java
- src/it/projects/GITHUB-1242/src/main/java/com/fruit/impl/Apple.java
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
_Partially_ reverts change in https://github.com/apache/maven-javadoc-plugin/pull/1217, specifically:
> Do not use --source-path in legacy mode as not to suck any of those module-info.java files back
This is required to ensure correct package resolution on projects that mix modular & non-module Java code.
Fixes: https://github.com/apache/maven-javadoc-plugin/issues/1242
> Fix `package {...} does not exist` in `legacyMode`
