apache/maven-javadoc-plugin

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> Add missing `@since` tags to sourceFile[Includes|Excludes]

- src/site/apt/examples/aggregate.apt.vm
> Remove space typo in  markdown

- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/c/d1/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/c/d1/src/main/java/a/b/c/d/D1.java
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/c/d2/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/c/d2/src/main/java/a/b/c/d/D2.java
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/c/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/e/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/e/src/main/java/a/b/e/E.java
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/b/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/f/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/f/src/main/java/a/f/F.java
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/invoker.properties
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/pom.xml
- src/it/projects/MJAVADOC-636-aggregate_module_skipped/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Signed-off-by: olivier lamy <olamy@apache.org>
To make clear that …
> [MJAVADOC-636] exclude some modules from aggregated javadoc

- pom.xml
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/invoker.properties
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulea/pom.xml
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulea/src/main/java/com/javamodularity/modulea/HelloWorld.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulea/src/main/java/module-info.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/moduleb/pom.xml
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/moduleb/src/main/java/com/javamodularity/moduleb/HelloWorld.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/moduleb/src/main/java/module-info.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulec/pom.xml
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulec/src/main/java/com/javamodularity/modulec/WorldCollector.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/modulec/src/main/java/module-info.java
- src/it/projects/MJAVADOC-639_aggr_static_modulepath/pom.xml
- src/it/projects/MJAVADOC-639_requires_ignored/invoker.properties
- src/it/projects/MJAVADOC-639_requires_ignored/modulea/pom.xml
- src/it/projects/MJAVADOC-639_requires_ignored/modulea/src/main/java/com/javamodularity/modulea/HelloWorld.java
- src/it/projects/MJAVADOC-639_requires_ignored/modulea/src/main/java/com/javamodularity/modulea/SimpleLogging.java
- src/it/projects/MJAVADOC-639_requires_ignored/modulea/src/main/java/module-info.java
- src/it/projects/MJAVADOC-639_requires_ignored/moduleb/pom.xml
- src/it/projects/MJAVADOC-639_requires_ignored/moduleb/src/main/java/com/javamodularity/moduleb/HelloWorld.java
- src/it/projects/MJAVADOC-639_requires_ignored/moduleb/src/main/java/module-info.java
- src/it/projects/MJAVADOC-639_requires_ignored/pom.xml
- src/it/projects/MJAVADOC-639_requires_ignored/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> [MJAVADOC-639] include requires static from external dependencies for all modules

- pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
To make clear that …
> [MJAVADOC-638] upgrade Doxia Sitetools to 1.9.2 to remove dependency on Struts

- src/it/projects/MJAVADOC-610_mrjar/invoker.properties
- src/it/projects/MJAVADOC-610_mrjar/pom.xml
- src/it/projects/MJAVADOC-610_mrjar/src/main/java/com/foo/MyClass.java
- src/it/projects/MJAVADOC-610_mrjar/src/main/java9/com/foo/MyClass.java
- src/it/projects/MJAVADOC-610_mrjar/src/main/java9/com/foo/OtherClass.java
- src/it/projects/MJAVADOC-610_mrjar/src/main/java9/module-info.java
- src/it/projects/MJAVADOC-610_mrjar/verify.groovy
> MJAVADOC-610

- pom.xml
> update misc apache dependencies

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
Related issue: https://issues.apache.org/jira/browse/MJAVADOC-614
> [MJAVADOC-614] - "No source files for package" in a directory with accent characters

- src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocUtilTest.java
> toURL --> toURI().toURL()

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/ResourcesBundleMojo.java
> replace deprecated method scheduled for removal and update archiver

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> (doc) Fix referenced parameter

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Because user can't do nothing with such message, and exception don't break execution,
logging in verbose mode with stacktrace will be enough.
---
[Individual Contributor License …
> [MJAVADOC-694] Avoid empty warn message from getResolvePathResult

- pom.xml
- src/main/java/org/apache/maven/plugins/javadoc/JavadocReport.java
Move to new API signature, but maintain old binary compatibility. This, in
general, can be avoided by extending AbstractMavenReport.
This closes #120
[Individual Contributor License …
> [MJAVADOC-705] Upgrade Maven Reporting API to 3.1.0

- .github/release-drafter.yml
- .github/workflows/maven.yml
- .github/workflows/release-drafter.yml
> use shared gh action/release-drafter

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> fix link to documentation of link option

- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
https://issues.apache.org/jira/browse/MNG-6825
To make clear that …
> [MNG-6825] Replace Maven shared StringUtils with Commons Lang3

- .github/pull_request_template.md
> Remove superflous whitespace from PR template

- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
Throw NPE, not IOException
To make clear that you license your …
> [MJAVADOC-758] correct exception in JavadocUtil

- src/site/xdoc/download.xml.vm
> [MJAVADOC-772] Refresh download page

- pom.xml
> [JAVADOC-771] Upgrade Parent to 40

- pom.xml
> fix jenkins link

- src/test/java/org/apache/maven/plugins/javadoc/JavadocUtilTest.java
Current version contains new element-list
---
To make clear that you …
> Use a stable link in unit test

- .gitignore
- pom.xml
> [MJAVADOC-774] Mock repository should not change project sources

- src/test/resources/unit/stale-test/stale-test-plugin-config.xml
https://issues.apache.org/jira/browse/MJAVADOC-780
> [MJAVADOC-780] add missing plugin configuration

- src/it/projects/MJAVADOC-498_modulepath/invoker.properties
- src/it/projects/MJAVADOC-580_detectLinks/invoker.properties
- src/it/projects/MJAVADOC-610_mrjar/invoker.properties
- src/it/projects/MJAVADOC-704_toolchains/invoker.properties
> Remove outdated invoker conditions

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> [MJAVADOC-803] Add default parameter to force root locale

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
Co-authored-by: Rob Gordon <rob@rgordon.co.uk>
Co-authored-by: Michael Osipov <michaelo@apache.org>
This closes #300
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you …
> [MJAVADOC-783] Invalid path when using TagletArtifact and TagletPath

- pom.xml
- src/it/projects/MJAVADOC-257/mymojo/pom.xml
- src/it/projects/MJAVADOC-257/pom.xml
- src/it/projects/MJAVADOC-568_manifest-splitpackage/mojo/pom.xml
- src/it/projects/MJAVADOC-569_aggr-mixed/module2/pom.xml
- src/it/projects/MJAVADOC-569_aggr-mixed/pom.xml
- src/it/projects/MJAVADOC-591_release8/pom.xml
- src/it/projects/dependencySource-4/MJAVADOC-280-4-projects/pom.xml
> Improve ITs

- src/main/java/org/apache/maven/plugins/javadoc/JavadocJarMojo.java
> [MJAVADOC-819] Align archive generation code with Maven Source Plugin

- .github/workflows/maven.yml
- src/it/projects/MJAVADOC-450_classifier-jdk-23/invoker.properties
- src/it/projects/MJAVADOC-450_classifier-jdk-23/pom.xml
- src/it/projects/MJAVADOC-450_classifier-jdk-23/src/main/java/com/foo/MyClass.java
- src/it/projects/MJAVADOC-450_classifier-jdk-23/verify.groovy
- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocJarMojoTest.java
- src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
- **test build with jdk23**
- **fix ghas**
- **some javadoc jdk 23 fixes**
- **add jdk23 specific test**
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
you have to acknowledge this by using the following …
> Issue #373 Fix JDK 23 build 

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
> Use Java 7 relativization instead of our hand-rolled code

- src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
There are actually two different toRelative methods used in this class, probably added at different times by different developers. This PR removes one of them.
> Use Java 7 relativization instead of hand-rolled code

- src/main/java/org/apache/maven/plugins/javadoc/JavadocUtil.java
Inlines and simplifies proxy checking code to break dependency on maven-wagon
Part 1 of #1207
> Decouple from wagon proxy classes

- pom.xml
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
> Maven Archiver 3.6.4

- .asf.yaml
> protect 3.8.x branch
